"use strict";

var _cliente = require("./cliente.js");
var _impuestos = require("./impuestos.js");
console.log("--------------------------------PROBANDO--------------------------------");
console.log("\n---Creando cliente 1, con nombre e impuesto---");
var i1 = new _impuestos.Impuestos(100, 10);
var c1 = new _cliente.Cliente("Mario", i1);
console.log("--Objeto Impuestos:");
console.log(i1);
console.log("--Objeto Cliente:");
console.log(c1);
console.log("get nombre() : ".concat(c1.nombre));
console.log("calcularImpuesto() : ".concat(c1.calcularImpuesto()));
console.log("--Cambio de nombre con setter:");
c1.nombre = "Luigi";
console.log("get nombre() : ".concat(c1.nombre));
console.log("--Cambio de impuesto y recalculando:");
c1.impuesto = new _impuestos.Impuestos(200, 50);
console.log("calcularImpuesto() : ".concat(c1.calcularImpuesto()));
console.log("\n---Creando cliente 2, con nombre y sin impuesto---");
var c2 = new _cliente.Cliente("Carla");
console.log("--Objeto Cliente:");
console.log(c2);
console.log("get nombre() : ".concat(c2.nombre));
console.log("calcularImpuesto() : ".concat(c2.calcularImpuesto()));
console.log("\n---Creando cliente 3, sin nombre ni impuesto---");
var c3 = new _cliente.Cliente();
console.log("--Objeto Cliente:");
console.log(c3);
console.log("get nombre() : ".concat(c3.nombre));
console.log("--Agregando de nombre con setter:");
c3.nombre = "Pedro";
console.log("get nombre() : ".concat(c3.nombre));
console.log("--Agregando impuesto:");
c3.impuesto = new _impuestos.Impuestos(66, 6);
console.log("--Objeto Impuesto:");
console.log(c3.impuesto);
console.log("calcularImpuesto() : ".concat(c3.calcularImpuesto()));